{"name": "a1-valves.com заказать звонок -- @1.1 ", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52509): Max retries exceeded with url: /session/7d62b791e5f18b7197021e3ff11da060/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113791570>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/behave/runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features/environment.py\", line 95, in after_step\n    bot.send_photo(chat_id=-447406725, photo=context.driver.get_screenshot_as_png(),\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1357, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1369, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 423, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 333, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 355, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/request.py\", line 66, in request\n    return self.request_encode_url(method, url, fields=fields,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/request.py\", line 89, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 324, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 637, in urlopen\n    retries = retries.increment(method, url, error=e, _pool=self,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/retry.py\", line 399, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "steps": [{"name": "Given open a1-valves.com page", "status": "passed", "start": 1667846550843, "stop": 1667846556908}, {"name": "When click on order call button in \"top menu section\"", "status": "passed", "start": 1667846556908, "stop": 1667846557465}, {"name": "When enter \"generated_test_automation_email_call_a1\" in name field in \"request call section\"", "status": "passed", "start": 1667846557465, "stop": 1667846558173}, {"name": "When enter \"+70000000000\" in phone field in \"request call section\"", "status": "passed", "start": 1667846558173, "stop": 1667846558778}, {"name": "When click on send button in \"request call section\"", "status": "passed", "start": 1667846558778, "stop": 1667846559342}, {"name": "Then email with \"generated_test_automation_email_call_a1\" contains \"Телефон : +70000000000\" in 900 sec", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52509): Max retries exceeded with url: /session/7d62b791e5f18b7197021e3ff11da060/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113791570>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/behave/runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features/environment.py\", line 95, in after_step\n    bot.send_photo(chat_id=-447406725, photo=context.driver.get_screenshot_as_png(),\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1357, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1369, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 423, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 333, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 355, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/request.py\", line 66, in request\n    return self.request_encode_url(method, url, fields=fields,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/request.py\", line 89, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 324, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 637, in urlopen\n    retries = retries.increment(method, url, error=e, _pool=self,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/retry.py\", line 399, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1667846559343, "stop": 1667846576375}, {"name": "Given open a1-valves.com page", "status": "passed", "start": 1667846576379, "stop": 1667846576379}, {"name": "When click on order call button in \"top menu section\"", "status": "passed", "start": 1667846576379, "stop": 1667846576379}, {"name": "When enter \"generated_test_automation_email_call_a1\" in name field in \"request call section\"", "status": "passed", "start": 1667846576379, "stop": 1667846576379}, {"name": "When enter \"+70000000000\" in phone field in \"request call section\"", "status": "passed", "start": 1667846576379, "stop": 1667846576379}, {"name": "When click on send button in \"request call section\"", "status": "passed", "start": 1667846576379, "stop": 1667846576379}, {"name": "Then email with \"generated_test_automation_email_call_a1\" contains \"Телефон : +70000000000\" in 900 sec", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52509): Max retries exceeded with url: /session/7d62b791e5f18b7197021e3ff11da060/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113791570>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/behave/runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features/environment.py\", line 95, in after_step\n    bot.send_photo(chat_id=-447406725, photo=context.driver.get_screenshot_as_png(),\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1357, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1369, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 423, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 333, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 355, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/request.py\", line 66, in request\n    return self.request_encode_url(method, url, fields=fields,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/request.py\", line 89, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 324, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 663, in urlopen\n    return self.urlopen(method, url, body, headers, retries,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 637, in urlopen\n    retries = retries.increment(method, url, error=e, _pool=self,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/retry.py\", line 399, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1667846576379, "stop": 1667846576379}], "parameters": [{"name": "section", "value": "top menu section"}], "start": 1667846550836, "stop": 1667846576379, "uuid": "dffb60dd-edd9-4d56-b137-de630e5b1b16", "historyId": "7faf572cfcca69d732baa5f93ff54721", "fullName": "Проверка сайта a1-valves.com: a1-valves.com заказать звонок", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "regression"}, {"name": "feature", "value": "Проверка сайта a1-valves.com"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}